on:
  push:
    paths:
      - '.github/workflows/cve_formatting.yml'
      - 'records/**/*.json'
      - '!records/reservations/*.json'

name: "CVE Formatting"

permissions:
  contents: read

jobs:
  check:
    name: "Check Formatting"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install Elixir
        uses: erlef/setup-beam@3580539ceec3dc05b0ed51e9e10b08eb7a7c2bb4 # v1.21.0
        with:
          elixir-version: '1.18.4'
          otp-version: '27.3.4.1'
      - name: Run Formatter
        run: './scripts/cve-formatter check-formatted'
