on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual trigger

name: "OSV Version Updates"

permissions:
  contents: read

jobs:
  update_versions:
    name: "Update OSV Affected Versions"
    runs-on: ubuntu-latest
    steps:
      - name: Login for PR
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        id: osv-app-token
        with:
          app-id: ${{ vars.CNA_BOT_APP_ID }}
          private-key: ${{ secrets.CNA_BOT_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: ${{ github.event.repository.name }}

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{ steps.osv-app-token.outputs.token }}

      - name: Install Elixir
        uses: erlef/setup-beam@e6d7c94229049569db56a7ad5a540c051a010af9 # v1.20.4
        with:
          elixir-version: '1.18.4'
          otp-version: '27.3.4.1'

      - name: Update OSV versions
        run: './scripts/cve-to-osv update-versions'

      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet osv/; then
            echo "No changes detected"
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected in OSV files"
            echo "changes=true" >> $GITHUB_OUTPUT
            # Show what changed
            git diff --stat osv/
          fi

      - name: Create or update PR
        if: steps.check_changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.osv-app-token.outputs.token }}
          commit-message: "chore(osv): update affected package versions"
          title: "Update OSV affected package versions"
          body: |
            This PR updates the affected versions in OSV files based on the latest package versions from hex.pm.

            This is an automated update that runs daily to ensure OSV files contain all affected versions.

            Changes in this PR:
            - Updated `versions` arrays in OSV files with newly published hex packages that are affected by the vulnerabilities
          labels: automated, osv-update
          branch: osv-version-updates
          delete-branch: true
          base: main